### ISSUE TITLE
react_render/priv/nodejs/server.js unable to locate js dependencies (react, react-dom,...)

### ISSUE THREAD

**Issue by komlanvi** [revelrylabs/elixir_react_render#22]
Sometimes I get this error when I rebuild my project and navigate to a page where react is rendered server side with `elixir_react_render`

```
no case clause matching: {:error, "Cannot find module 'react-dom/server'\nError: Cannot find module 'react-dom/server'\n at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)\n at Function.Module._load (internal/modules/cjs/loader.js:507:25)\n at Module.require (internal/modules/cjs/loader.js:637:17)\n at require (internal/modules/cjs/helpers.js:22:18)\n at Object.<anonymous> (/code/deps/react_render/priv/nodejs/server.js:1:83)\n at Module._compile (internal/modules/cjs/loader.js:689:30)\n at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n at Module.load (internal/modules/cjs/loader.js:599:32)\n at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n at Function.Module._load (internal/modules/cjs/loader.js:530:3)"}
```
Here is the first lines of the `deps/react_render/priv/nodejs/server.js` where the problem occur:
![Screenshot from 2019-03-18 19-18-19](https://user-images.githubusercontent.com/8933992/54553535-abfcf980-49b2-11e9-8ed2-f74f17ee4c30.png)

And here is my package.json 
![Screenshot from 2019-03-18 18-33-48](https://user-images.githubusercontent.com/8933992/54550535-75bc7b80-49ac-11e9-9ac7-62a091905a16.png)

**Comment by kordeviant** [comment]
same here
```
{"Kernel pid terminated",application_controller,"{application_start_failure,hello,{{shutdown,{failed_to_start_child,'Elixir.ReactRender',{shutdown,{failed_to_start_child,'Elixir.NodeJS.Supervisor',{shutdown,{failed_to_start_child,nodejs,{{badmatch,{error,{enoent,[{erlang,open_port,[{spawn_executable,nil},[{line,65536},{env,[{\"NODE_PATH\",\"/app/lib/react_render-2.0.2/priv/nodejs\"},{\"WRITE_CHUNK_SIZE\",\"65536\"}]},{args,[<<\"/app/lib/nodejs-1.0.0/priv/server.js\">>]}]],[]},{'Elixir.NodeJS.Worker',init,1,[{file,\"lib/nodejs/worker.ex\"},{line,29}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,374}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,249}]}]}}},[{poolboy,new_worker,1,[{file,\"/tmp/build/deps/poolboy/src/poolboy.erl\"},{line,283}]},{poolboy,prepopulate,3,[{file,\"/tmp/build/deps/poolboy/src/poolboy.erl\"},{line,304}]},{poolboy,init,3,[{file,\"/tmp/build/deps/poolboy/src/poolboy.erl\"},{line,153}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,374}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,249}]}]}}}}}}},{'Elixir.Hello.Application',start,[normal,[]]}}}"}
```

**Comment by oohnoitz** [comment]
Going to mark this closed, since it should be resolved in the latest release. We can re-open it if it is still happening.
